// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "15853220-b9eb-478a-8d57-a90a2afbefb9");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1663719761);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1663720009);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{b4f5e473-28c8-4f47-b59c-a823a88e0fb8}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1663719758);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 128);
user_pref("browser.newtabpage.activity-stream.impressionId", "{1c25a0d0-fd0c-4046-a45f-2c407556b65b}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1663719759);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1663719762001");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1663741362001");
user_pref("browser.search.region", "BR");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20220902153754");
user_pref("browser.shell.defaultBrowserCheckCount", 2);
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20220902153754");
user_pref("browser.startup.homepage_override.mstone", "104.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1663720009);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1663719760489");
user_pref("distribution.iniFile.exists.appversion", "104.0.2");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "BR");
user_pref("dom.push.userAgentID", "b23c1f5585b04a079bb0d11c20a6aa1a");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20220902153754");
user_pref("extensions.lastAppVersion", "104.0.2");
user_pref("extensions.lastPlatformVersion", "104.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"714c7edc-d950-4128-be5d-ada078f45a9b\",\"formautofill@mozilla.org\":\"3cb5ae5d-fb25-4530-950e-1d1f1efa947d\",\"pictureinpicture@mozilla.org\":\"a205b342-7ea6-4f02-a6c3-c134ae625fbf\",\"screenshots@mozilla.org\":\"afbfe94e-ee8d-4108-a11c-2b21bdd5477c\",\"webcompat-reporter@mozilla.org\":\"09df34ee-a510-44d1-8dc5-8b5a151f43f9\",\"webcompat@mozilla.org\":\"bee26f4d-c6b2-4243-9ccd-2222be21633b\",\"default-theme@mozilla.org\":\"10d7cc75-335b-4206-bf1a-4a60110a87c7\",\"addons-search-detection@mozilla.com\":\"e5bcc16b-2c6f-494c-9a9b-b8857d952e44\",\"google@search.mozilla.org\":\"9e389364-04c1-4274-a593-7907d8067125\",\"amazondotcom@search.mozilla.org\":\"bc0d9397-86c1-4244-af65-4ffb3809f254\",\"wikipedia@search.mozilla.org\":\"c6667148-c238-4e8d-b891-f84d534ec24f\",\"bing@search.mozilla.org\":\"d481c68e-461c-4638-b936-5f19c6d0525c\",\"ddg@search.mozilla.org\":\"29eda851-c51d-4ec2-afcc-31b6828ff7a2\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1663719759);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("nimbus.syncdatastore.tcpByDefault", "{\"slug\":\"tcp-rollout-phase-iii-tcp-on-by-default-for-95-existing-release-profiles\",\"branch\":{\"slug\":\"control\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"tcpByDefault\"},\"features\":null},\"active\":true,\"enrollmentId\":\"44d20de9-0067-4dcc-be9f-2135e3d27bf4\",\"experimentType\":\"nimbus\",\"source\":\"rs-loader\",\"userFacingName\":\"TCP rollout, Phase III (TCP on by default for 95% EXISTING Release profiles)\",\"userFacingDescription\":\"\\\"By default\\\" rollout: Gradually turning on Total Cookie Protection in standard browsing by default for EXISTING user profiles\",\"lastSeen\":\"2022-09-21T00:22:39.795Z\",\"featureIds\":[\"tcpByDefault\"]}");
user_pref("nimbus.syncdatastore.tcpByDefault.enabled", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "8a3b565f-4e05-4db6-af82-5c1980894d98");
user_pref("toolkit.startup.last_success", 1663720008);
user_pref("toolkit.telemetry.cachedClientID", "38e9c089-5762-4827-a632-d8b0a06299dd");
user_pref("toolkit.telemetry.previousBuildID", "20220902153754");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
